
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/address-pool: ip-pools
spec:
  type: LoadBalancer
  ports:
  - name: phpmyadmin
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: phpmyadmin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin
        imagePullPolicy: Never
        env:
        - name: MYSQL_IP
          value: mysql-service.default.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /
            port: 5000
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 5000
