apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/address-pool: ip-pools
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_wordpress
        imagePullPolicy: Never
        env:
        - name: MYSQL_IP
          value: mysql-service.default.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /
            port: 5050
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 5050
